/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function openDevtools() {
    return invoke()<null>("open_devtools")
}

export function killProcess(pid: number) {
    return invoke()<number[]>("kill_process", { pid })
}

export function spawnProcess(channelId: string, programm: string, args: string[], cwd: string, env: { [key: string]: string }) {
    return invoke()<number>("spawn_process", { channelId,programm,args,cwd,env })
}


